export const guests = [
  { name: "Alma Guadalupe De la Rosa", confirmed: false },
  { name: "Brenda Arroyos", confirmed: false },
  { name: "Brenda Hurtado", confirmed: false },
  { name: "Carolina Rodríguez", confirmed: false },
  { name: "César Martínez", confirmed: false },
  { name: "Cirilo Reyes", confirmed: false },
  { name: "Daniel Aguilar", confirmed: false },
  { name: "Guadalupe Martínez", confirmed: false },
  { name: "Jonathan Sánchez", confirmed: false },
  { name: "José Antonio Aguilar", confirmed: false },
  { name: "Josue Narváez", confirmed: false },
  { name: "Karla García", confirmed: false },
  { name: "Lorena Trujillo", confirmed: false },
  { name: "Manuel Macías", confirmed: false },
  { name: "Mario Bautista", confirmed: false },
  { name: "Miranda Jaramillo", confirmed: false },
  { name: "Nancy Zuñiga", confirmed: false },
  { name: "Oscar Ricardo Martínez", confirmed: false },
  { name: "Raul Vázquez", confirmed: false },
  { name: "Rebeca García", confirmed: false },
  { name: "Ricardo Martínez", confirmed: false },
  { name: "Ricardo Pérez", confirmed: false },
  { name: "Ricardo Rivera", confirmed: false },
  { name: "Sofía Galindo", confirmed: false },
  { name: "Susana Bautista", confirmed: false },
];
