export const guests = [
  { name: "Ricardo Martinez", confirmed: false },
  { name: "Daniel Aguilar", confirmed: false },
  { name: "José Antonio Aguilar", confirmed: false },
  { name: "Guadalupe Martínez", confirmed: false },
  { name: "Nancy Zuñiga", confirmed: false },
  { name: "Tía Carolina", confirmed: false },
  { name: "María Bautista", confirmed: false },
  { name: "Cirilo Reyes", confirmed: false },
  { name: "Susana Bautista", confirmed: false },
  { name: "Mario Bautista", confirmed: false },
  { name: "Celia Bautista", confirmed: false },
  { name: "Ricardo Perez", confirmed: false },
  { name: "Lorena Trujillo", confirmed: false },
  { name: "Rebeca García", confirmed: false },
  { name: "Manuel Macias", confirmed: false },
  { name: "Ricardo Rivera", confirmed: false },
  { name: "Josue Narváez", confirmed: false },
  { name: "Karla García", confirmed: false },
  { name: "Alma Guadalupe De la Rosa", confirmed: false },
  { name: "Brenda Arroyos", confirmed: false },
  { name: "Sofía Galindo", confirmed: false },
  { name: "Miranda Jaramillo", confirmed: false },
  { name: "Miss Susana Acero", confirmed: false },
  { name: "Damaris Franco", confirmed: false },
];
